<a href="https://colab.research.google.com/github/heysourin/Machine-Learning-101/blob/main/Cross%20Validation/k_fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_digits
digits = load_digits()

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [42]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1257, 64), (1257,), (540, 64), (540,))

In [43]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

In [44]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [45]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [66]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [67]:
for train_split, test_split in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
  print(train_split, test_split)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [48]:
def get_score(model, X_train, y_train, X_test, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [49]:
get_score(LogisticRegression(), X_train, y_train, X_test, y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

In [50]:
get_score(SVC(), X_train, y_train, X_test, y_test)

0.9925925925925926

In [76]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [ ]:
scores_l = []
scores_svm = []
scores_rf = []

for train_split, test_split in kf.split(digits.data):
  X_train, X_test, y_train, y_test = digits.data[train_split], digits.data[test_split],\
                                    digits.target[train_split], digits.target[test_split]

  scores_l.append(get_score(LogisticRegression(), X_train, y_train, X_test, y_test))
  scores_svm.append(get_score(SVC(), X_train, y_train, X_test, y_test))
  scores_rf.append(get_score(RandomForestClassifier(), X_train, y_train, X_test, y_test))

In [69]:
scores_l

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]

In [70]:
scores_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [71]:
scores_rf

[0.9416666666666667,
 0.9111111111111111,
 0.9637883008356546,
 0.947075208913649,
 0.9220055710306406]

## **Note:** You can do the above thing using a library only

In [78]:
from sklearn.model_selection import cross_val_score

In [79]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [82]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [84]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=6)

array([0.93      , 0.97      , 0.94333333, 0.98327759, 0.97324415,
       0.91638796])